apiVersion: v1
kind: Service
metadata: 
  name: myapp-service
  
spec:
  type: NodePort
  ports:
    - nodePort: 30008
      port: 8080
      targetPort: 80
      
  selector:
    app: myapp
    type: front-end
    
